version: '3.8'

services:
  frontend:
    image: flomihciu/nginx-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: flomihciu/flask-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - CONNECTION_STRING=${DB_CONNECTION_STRING}
    depends_on:
      - database
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/movies"]
      interval: 30s
      retries: 3

  database:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER"]
      interval: 30s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
