version: '3.8'

services:
  frontend:
    image: flomihciu/nginx-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: flomihciu/flask-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/movies"]
      interval: 30s
      retries: 3

networks:
  app-network:
    driver: bridge
