- name: Deploy Movie DB App
  hosts: web
  become: true

  tasks:
    - name: Install Docker & Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: true

    - name: Copy docker-compose.yml to EC2
      ansible.builtin.copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Copy .env file to EC2
      ansible.builtin.copy:
        src: ../.env
        dest: /home/ubuntu/.env

    - name: Ensure containers are running with Docker Compose v2
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
        state: present

    - name: Wait for backend app to respond
      ansible.builtin.shell: curl -s -o /dev/null -w "%{http_code}" http://localhost:5000 || true
      register: backend_status
      retries: 20
      delay: 3
      until: backend_status.stdout == "200"

    - name: Fail if backend app did not return 200
      ansible.builtin.fail:
        msg: "Backend app is not responding as expected!"
      when: backend_status.stdout != "200"

    - name: Debug backend status code
      ansible.builtin.debug:
        msg: "Backend responded with status code: {{ backend_status.stdout }}"
